#SPDX-License-Identifier: MIT-0
---
- name: "Cleanup: Remove GitLab installation files and scripts"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/root/{{ gls_ruby_script }}"

- name: "Cleanup: Remove temporary directory for scripts"
  ansible.builtin.file:
    path: "{{ gitlab_rb_scripts_tempdir.path }}"
    state: absent
  when: gitlab_rb_scripts_tempdir.path is defined
...