---

- name: Check installed packages
  ansible.builtin.package_facts:

- name: "Show installed GitLab version"
  when: gitlab_package_name in ansible_facts.packages
  ansible.builtin.debug:
    msg:
      - "GitLab is already installed"
      - "Version: {{ ansible_facts.packages[gitlab_package_name][0].version }}"

- name: Download and Install GitLab
  when: not gitlab_package_name in ansible_facts.packages
  block:
    # - name: "Download GitLab installation file"
    #   ansible.builtin.get_url:
    #     url: "{{ nexus_url }}{{ gitlab_installation_file }}"
    #     dest: "/tmp/{{ gitlab_installation_file }}"
    #     mode: '0755'
    #     username: "{{ nexus_user_code }}"
    #     password: "{{ nexus_password }}"

    - name: Copy gitlab file to remote host
      ansible.builtin.copy:
        src: "files/{{ gitlab_installation_file }}"
        dest: "/tmp/{{ gitlab_installation_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: "Install GitLab"
      ansible.builtin.dnf:
        name: "/tmp/{{ gitlab_installation_file }}"
        disable_gpg_check: true
        state: present
    
