#SPDX-License-Identifier: MIT-0
---
- name: "Main: Validate required variables"
  ansible.builtin.include_tasks: "assert.yml"

- name: "Main: Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Main: Prepare RedHat environment"
  ansible.builtin.include_tasks: "prepare_redhat.yml"
  when: ansible_os_family == 'RedHat'

- name: "Main: Prepare Debian environment"
  ansible.builtin.include_tasks: "prepare_debian.yml"
  when: ansible_os_family == 'Debian'

- name: "Main: Install GitLab on RedHat"
  ansible.builtin.include_tasks: "install_redhat.yml"
  when: ansible_os_family == 'RedHat'

- name: "Main: Install GitLab on Debian"
  ansible.builtin.include_tasks: "install_debian.yml"
  when: ansible_os_family == 'Debian'

- name: "Main: Configure SSL"
  ansible.builtin.include_tasks: "ssl.yml"

- name: "Main: Configure and Reconfigure GitLab"
  ansible.builtin.include_tasks: "configure.yml"

- name: "Main: Configure GitLab with Ruby scripts"
  ansible.builtin.include_tasks: "gitlab_ruby_configuration.yml"

- name: "Main: Cleanup environment after installation"
  ansible.builtin.include_tasks: "cleanup.yml"
...