#SPDX-License-Identifier: MIT-0
---
# tasks file for ro_gitlab_present
- name: "Main: Prepare environment before starting installation"
  include_tasks: "prepare.yml"
  when: false

- name: "Main: Install GitLab"
  include_tasks: "install.yml"
  when: false

- name: "Main: Reconfigure GitLab"
  include_tasks: "reconfigure.yml"
  when: false

- name: "Main: Configure GitLab with Ruby scripts"
  include_tasks: "gitlab_ruby_configuration.yml"

- name: "Main: Cleanup environment after installation"
  include_tasks: "cleanup.yml"
  when: false