---
- name: "Check dnf $releasever variable via Python"
  ansible.builtin.command: >
    python3 -c 'import dnf; db = dnf.Base(); db.conf.read(); print(db.conf.substitutions.get("releasever", "Unknown"))'
  register: dnf_releasever
  changed_when: false

- name: "Display the release version"
  ansible.builtin.debug:
    msg: "The detected RHEL release version is: {{ dnf_releasever.stdout | trim }}"

# - name: "Check database connection"
#   ansible.builtin.include_role:
#     name: ro_gitlab_health_check
#   vars:
#     ro_gitlab_health_check__check: "database"

# - name: "Abort Gitlab installation"
#   ansible.builtin.fail:
#     msg: "Abort installation process due to connection error to the configured database."
#   when:
#     ro_gitlab_health_check__failure
#     or
#     not ro_gitlab_health_check__success

# - meta: end_play

- name: Install python3-libdnf using raw command
  ansible.builtin.raw: dnf install -y python3-libdnf

- name: Install required dependencies
  ansible.builtin.dnf:
    name:
      - yum-utils
      - tar
      - tmux
      - which
      - lsof
      - curl
      - openssl
      - postfix
      - firewalld
      - python3-cryptography
      - python3-psycopg2
      - postgresql
    state: present
    use_backend: dnf4

- name: Start firewall daemon
  ansible.builtin.service:
    name: firewalld.service
    state: started
    enabled: true

- name: Open webserver ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - http
    - https

- name: Restart the firewall daemon
  ansible.builtin.service:
    name: firewalld.service
    state: restarted
  changed_when: false

    