---
- name: "Gitlab reconfigure"
  block:
    - name: "Reconfigure Gitlab"
      ansible.builtin.command: "gitlab-ctl reconfigure"
      ignore_errors: true
      async: 1200
      poll: 0
      changed_when: false
      register: gitlab_reconfigure
      
    - name: "Show reconfigure output"
      ansible.builtin.debug:
        var: gitlab_reconfigure.stdout