#SPDX-License-Identifier: MIT-0
---
# handlers/main.yml

- name: "Restart gitlab-runner container"
  containers.podman.podman_container:
    name: "{{ gitlab_runner_container_name }}"
    state: started
    restart: true

- name: "Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true

...
