---
- name: Install Gitlab server
  hosts: vm_test2
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: true
  become: true
  vars_files:
    - ./credentials.yml

  tasks:
    - name: "Display detected OS family"
      ansible.builtin.debug:
        msg: "Target OS: {{ ansible_distribution }} {{ ansible_distribution_version }} (Family: {{ ansible_os_family }})"
        verbosity: 1

    - name: "Include Ansible role to install Gitlab Server"
      ansible.builtin.include_role:
        name: ro_gitlab_present
      vars:
        gls_domain: "{{ ip_address_v4 | default(ansible_host) }}"
...
