#SPDX-License-Identifier: MIT-0
---
- name: Verify
  hosts: all
  tasks:
    - name: "Check if GitLab is running"
      ansible.builtin.uri:
        url: "https://127.0.0.1/-/readiness"
        status_code: 200
        validate_certs: false
        return_content: true
      register: readiness
      retries: 10
      delay: 5
      until: readiness.status == 200
