galaxy_info:
  author: StandardNerd
  description: Ansible role for installing and configuring GitLab CE/EE on RHEL 9 and Ubuntu Noble.
  company: StandardNerd
  license: MIT-0
  min_ansible_version: 2.12
  platforms:
    - name: EL
      versions:
        - 9
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - gitlab
    - rhel
    - ubuntu
dependencies: []
