#SPDX-License-Identifier: MIT-0
---
gls_os_packages:
  - apt-transport-https
  - tar
  - tmux
  - lsof
  - curl
  - openssl
  - postfix
  - ufw
  - python3-cryptography
  - python3-psycopg2
  - postgresql-client

gls_firewall_service: ufw
gls_web_ports:
  - http
  - https
...
