#SPDX-License-Identifier: MIT-0
---
- name: "Reconfigure GitLab"
  ansible.builtin.command: "gitlab-ctl reconfigure"
  changed_when: true

- name: "Restart GitLab"
  ansible.builtin.command: "gitlab-ctl restart"
  changed_when: true

- name: "Reload firewalld"
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: ansible_os_family == 'RedHat'

- name: "Reload ufw"
  community.general.ufw:
    state: reloaded
  when: ansible_os_family == 'Debian'

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
...